version: '3.8'

# Подключаем файл .env для всех сервисов
env_file:
  - .env

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Django-переменные
      DEBUG: "${DEBUG}"
      SECRET_KEY: "${SECRET_KEY}"
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"

      # Переменные для подключения к Postgres
      DATABASE_NAME: "${POSTGRES_DB}"
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_HOST: "db"
      DATABASE_PORT: "${DATABASE_PORT}"
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet: